// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OngBackEnd.DataContext;

namespace OngBackEnd.Migrations
{
    [DbContext(typeof(ONGDataContext))]
    [Migration("20190725214007_ImpDb")]
    partial class ImpDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OngBackEnd.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Direccion");

                    b.Property<DateTime>("FechaN");

                    b.Property<string>("Grado");

                    b.Property<string>("Nombre");

                    b.Property<int>("Seccion");

                    b.Property<string>("pass");

                    b.HasKey("IdAlumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("OngBackEnd.Models.Asignatura", b =>
                {
                    b.Property<int>("IdAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Asignatur");

                    b.Property<int>("IdGrado");

                    b.HasKey("IdAsignatura");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("OngBackEnd.Models.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Grados");

                    b.Property<string>("Jornada");

                    b.HasKey("IdGrado");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("OngBackEnd.Models.GradoMaestro", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Grado");

                    b.Property<string>("Jornada");

                    b.HasKey("IdGrado");

                    b.ToTable("GradoMaestros");
                });

            modelBuilder.Entity("OngBackEnd.Models.HistorialAc", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdSemestre");

                    b.Property<int>("Notas");

                    b.Property<string>("Observaciones");

                    b.HasKey("IdAlumno");

                    b.ToTable("HistorialAcs");
                });

            modelBuilder.Entity("OngBackEnd.Models.Maestro", b =>
                {
                    b.Property<int>("IdMaestro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Grado");

                    b.Property<string>("Nombre");

                    b.Property<string>("Seccion");

                    b.Property<string>("pass");

                    b.HasKey("IdMaestro");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("OngBackEnd.Models.MaestroAsignatura", b =>
                {
                    b.Property<int>("IdMaestro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAsignatura");

                    b.HasKey("IdMaestro");

                    b.ToTable("MaestroAsignaturas");
                });

            modelBuilder.Entity("OngBackEnd.Models.Nota", b =>
                {
                    b.Property<int>("IdSemestre")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAlumno");

                    b.Property<int>("IdAsignatura");

                    b.Property<int>("NotaAcum");

                    b.Property<int>("NotaExa");

                    b.Property<int>("P1");

                    b.Property<int>("P2");

                    b.Property<int>("P3");

                    b.Property<int>("P4");

                    b.Property<int>("Total");

                    b.HasKey("IdSemestre");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("OngBackEnd.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TRol");

                    b.HasKey("IdRol");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("OngBackEnd.Models.Semestre", b =>
                {
                    b.Property<int>("IdSemestre")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NSemestre");

                    b.HasKey("IdSemestre");

                    b.ToTable("Semestres");
                });
#pragma warning restore 612, 618
        }
    }
}
